name: Clean Install Dependencies

on:
  workflow_dispatch:

jobs:
  clean-install:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clean install all dependencies
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USER }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          echo "=== LIMPIEZA COMPLETA DE DEPENDENCIAS ==="
          
          cd /home/*/billeo-app || cd ~/billeo-app
          
          # Parar todas las aplicaciones PM2
          pm2 stop all || true
          pm2 delete all || true
          
          echo "=== Eliminando node_modules corrupto ==="
          rm -rf node_modules
          rm -rf package-lock.json
          
          echo "=== Verificando espacio en disco ==="
          df -h
          
          echo "=== Limpiando cache de npm ==="
          npm cache clean --force
          
          echo "=== Instalando dependencias desde cero ==="
          npm install
          
          echo "=== Verificando instalación ==="
          ls -la node_modules/ | head -20
          
          echo "=== Verificando dotenv específicamente ==="
          ls -la node_modules/dotenv/ || echo "dotenv no instalado"
          
          echo "=== Verificando drizzle-orm ==="
          ls -la node_modules/drizzle-orm/ || echo "drizzle-orm no instalado"
          
          echo "=== Probando importación de dotenv ==="
          node -e "console.log('dotenv test:', require('dotenv'))" || echo "Error importando dotenv"
          
          echo "=== Intentando correr en desarrollo ==="
          pm2 start "tsx server/index.ts" --name billeo-clean --env development || true
          
          sleep 3
          pm2 logs billeo-clean --lines 5 || true
          pm2 status 