name: Deploy to Lightsail

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy to Lightsail
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install all dependencies
        run: npm ci
      
      - name: Build frontend and backend
        run: |
          # Build frontend
          cd client
          npm ci
          npm run build
          cd ..
          
          # Build backend (esto genera dist/index.js)
          npm run build
          
          # Verificar que todo está compilado
          ls -la dist/
          ls -la dist/public/
      
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
      
      - name: Deploy compiled app to server
        run: |
          # Crear directorio
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} 'mkdir -p /home/ubuntu/billeo'
          
          # Subir solo archivos necesarios para producción
          rsync -avz dist/ ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/home/ubuntu/billeo/dist/
          rsync -avz package.json ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/home/ubuntu/billeo/
          rsync -avz database.db ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/home/ubuntu/billeo/ || echo "No database.db found"
          rsync -avz uploads/ ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/home/ubuntu/billeo/uploads/ || echo "No uploads found"
      
      - name: Install production dependencies and start app
        run: |
          # Solo instalar dependencias de runtime (mucho más rápido)
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} 'cd /home/ubuntu/billeo && npm install --production --only=prod'
          
          # Iniciar aplicación compilada
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} 'cd /home/ubuntu/billeo && pm2 restart billeo || pm2 start dist/index.js --name billeo' 