name: Fix Nginx - HTTP Only

on:
  workflow_dispatch:

jobs:
  fix-nginx:
    runs-on: ubuntu-latest
    
    steps:
    - name: Fix Nginx Configuration
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USER }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          echo "=== Arreglando configuración de Nginx ==="
          
          # Parar nginx
          sudo systemctl stop nginx
          
          # Crear configuración solo HTTP (temporal)
          sudo tee /etc/nginx/sites-available/billeo << 'EOF'
          server {
              listen 80;
              server_name app.billeo.es;
              
              client_max_body_size 50M;
              
              location / {
                  proxy_pass http://localhost:3000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_set_header X-Forwarded-Host $server_name;
                  
                  # WebSocket support
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";
                  
                  # Timeouts
                  proxy_connect_timeout 60s;
                  proxy_send_timeout 60s;
                  proxy_read_timeout 60s;
              }
              
              # Static files caching
              location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
                  proxy_pass http://localhost:3000;
                  expires 1y;
                  add_header Cache-Control "public, immutable";
              }
          }
          EOF
          
          # Verificar configuración
          sudo nginx -t
          
          # Iniciar nginx
          sudo systemctl start nginx
          sudo systemctl enable nginx
          
          # Verificar estado
          sudo systemctl status nginx --no-pager
          
          echo -e "\n=== Probando conexión ==="
          sleep 2
          curl -I http://localhost:80 2>/dev/null | head -n 1 || echo "Nginx no responde"
          
          echo -e "\n=== Estado de PM2 ==="
          pm2 status
          
          echo -e "\n✅ Nginx configurado correctamente (solo HTTP)"
          echo "Accesible en: http://app.billeo.es"
          echo "Próximo paso: Configurar SSL con Let's Encrypt" 