name: Run App in Development Mode

on:
  workflow_dispatch:

jobs:
  run-dev:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run app in development mode
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USER }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          echo "=== CORRIENDO APP EN MODO DESARROLLO ==="
          
          cd /home/*/billeo-app || cd ~/billeo-app
          
          # Parar versión compilada
          pm2 stop billeo-app || true
          pm2 delete billeo-app || true
          
          # Instalar tsx si no está
          sudo npm install -g tsx || true
          
          # Verificar dependencias completas (no production)
          echo "=== Instalando dependencias completas ==="
          npm install
          
          # Verificar archivos
          echo "=== Archivos del proyecto ==="
          ls -la
          ls -la server/
          
          # Crear archivo .env básico si no existe
          echo "=== Configurando variables de entorno ==="
          echo "NODE_ENV=development" > .env
          echo "PORT=3000" >> .env
          echo "DATABASE_URL=file:database.db" >> .env
          
          # Ejecutar en modo desarrollo con PM2
          echo "=== Iniciando en modo desarrollo ==="
          pm2 start "tsx server/index.ts" --name billeo-app-dev --env development
          
          # Ver logs inmediatos
          echo "=== LOGS INICIALES ==="
          sleep 3
          pm2 logs billeo-app-dev --lines 10
          
          # Verificar estado
          echo "=== ESTADO PM2 ==="
          pm2 status
          
          # Probar conexión local
          echo "=== PRUEBA LOCAL ==="
          sleep 2
          curl -I http://localhost:3000 || echo "No responde aún" 