name: Setup Nginx Proxy

on:
  workflow_dispatch:

jobs:
  setup-nginx:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Nginx on server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USER }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          echo "=== Instalando y configurando Nginx ==="
          
          # Instalar nginx
          sudo apt update
          sudo apt install -y nginx
          
          # Parar nginx para configurarlo
          sudo systemctl stop nginx
          
          # Backup configuración original
          sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup
          
          # Crear configuración para Billeo
          sudo tee /etc/nginx/sites-available/billeo << 'EOF'
          server {
              listen 80;
              server_name app.billeo.es;
              
              # Redirect to HTTPS
              return 301 https://$server_name$request_uri;
          }
          
          server {
              listen 443 ssl http2;
              server_name app.billeo.es;
              
              # SSL certificates (temporal, usaremos Let's Encrypt después)
              ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
              ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
              
              ssl_protocols TLSv1.2 TLSv1.3;
              ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384;
              ssl_prefer_server_ciphers off;
              
              client_max_body_size 50M;
              
              location / {
                  proxy_pass http://localhost:3000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_set_header X-Forwarded-Host $server_name;
                  
                  # WebSocket support
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";
                  
                  # Timeouts
                  proxy_connect_timeout 60s;
                  proxy_send_timeout 60s;
                  proxy_read_timeout 60s;
              }
              
              # Static files caching
              location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
                  proxy_pass http://localhost:3000;
                  expires 1y;
                  add_header Cache-Control "public, immutable";
              }
          }
          EOF
          
          # Habilitar el sitio
          sudo ln -sf /etc/nginx/sites-available/billeo /etc/nginx/sites-enabled/
          
          # Eliminar sitio por defecto
          sudo rm -f /etc/nginx/sites-enabled/default
          
          # Verificar configuración
          sudo nginx -t
          
          # Configurar firewall para nginx
          sudo ufw allow 'Nginx Full'
          sudo ufw allow ssh
          
          # Iniciar nginx
          sudo systemctl start nginx
          sudo systemctl enable nginx
          
          # Verificar estado
          sudo systemctl status nginx --no-pager
          
          echo "=== Nginx configurado correctamente ==="
          echo "HTTP: http://app.billeo.es → http://localhost:3000"
          echo "HTTPS: https://app.billeo.es → http://localhost:3000"
          echo ""
          echo "Próximo paso: Configurar SSL con Let's Encrypt" 